import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/navigation/Navbar';
import NotificationContainer from '@/components/notification/NotificationContainer';
import Profile from '@/components/profile/Profile';
import { Suspense } from 'react';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <script
                    src="https://unpkg.com/react-scan/dist/auto.global.js"
                    async
                />
            </head>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased font-[family-name:var(--font-geist-sans)]`}
            >
                <div className="grid grid-rows-[auto,1fr] h-screen">
                    <Navbar>
                        <NotificationContainer />
                        {/* TODO: Profile skeleton */}
                        <Suspense fallback={<div>Profile loading...</div>}>
                            <Profile />
                        </Suspense>
                    </Navbar>
                    {children}
                </div>
            </body>
        </html>
    );
}
